"""
Configuration loader for source scrapers.
"""
import json
import os
from pathlib import Path
from typing import Dict, Optional

from app.scrapers.base import BaseScraper


class SourceConfig:
    """Source configuration model."""
    
    def __init__(self, config_dict: Dict):
        self.source_id = config_dict.get('sourceId')
        self.source_name = config_dict.get('sourceName')
        self.base_url = config_dict.get('baseUrl')
        self.city = config_dict.get('city', 'Gdańsk')
        self.facility_name = config_dict.get('facilityName', self.source_name)
        
        # Selectors
        selectors = config_dict.get('selectors', {})
        self.job_list_container = selectors.get('jobListContainer')
        self.job_item = selectors.get('jobItem')
        self.title_selector = selectors.get('title')
        self.link_selector = selectors.get('link')
        self.description_selector = selectors.get('description')
        self.date_selector = selectors.get('date')
        
        # Extraction hints
        extraction = config_dict.get('extraction', {})
        self.title_from = extraction.get('titleFrom', 'text')
        self.link_from = extraction.get('linkFrom', 'href')
        self.normalize_link = extraction.get('normalizeLink', True)
        
        # Pagination
        pagination = config_dict.get('pagination', {})
        self.pagination_type = pagination.get('type', 'none')
        self.pagination_param = pagination.get('param', 'page')
        self.max_pages = pagination.get('maxPages', 10)
        
        # Metadata
        metadata = config_dict.get('metadata', {})
        self.confidence = metadata.get('confidence', 'LOW')
        self.auto_generated = metadata.get('autoGenerated', False)
        self.notes = metadata.get('notes', '')
        
        # Store full config for saving
        self._config_dict = config_dict
    
    def to_dict(self) -> Dict:
        """Convert config back to dictionary."""
        return self._config_dict
    
    @classmethod
    def from_file(cls, config_path: str) -> 'SourceConfig':
        """Load config from JSON file."""
        with open(config_path, 'r', encoding='utf-8') as f:
            config_dict = json.load(f)
        return cls(config_dict)
    
    def save(self, config_path: str):
        """Save config to JSON file."""
        with open(config_path, 'w', encoding='utf-8') as f:
            json.dump(self._config_dict, f, indent=2, ensure_ascii=False)


def get_configs_dir() -> Path:
    """Get the directory where configs are stored."""
    return Path(__file__).parent / 'configs'


def load_config(source_id: str) -> Optional[SourceConfig]:
    """Load a source config by ID."""
    config_path = get_configs_dir() / f"{source_id}.json"
    if not config_path.exists():
        return None
    return SourceConfig.from_file(str(config_path))


def list_configs() -> list:
    """List all available config IDs."""
    configs_dir = get_configs_dir()
    if not configs_dir.exists():
        return []
    
    config_files = list(configs_dir.glob('*.json'))
    return [f.stem for f in config_files]


def save_config(config: SourceConfig):
    """Save a source config."""
    configs_dir = get_configs_dir()
    configs_dir.mkdir(exist_ok=True)
    
    config_path = configs_dir / f"{config.source_id}.json"
    config.save(str(config_path))

